<?php
"data": [
    {
      "id_order": "1",
      "token_customer": "123",
      "telp_customer": "+6281231391835",
      "token_vendor": null,
      "id_vendor": "1",
      "telp_vendor": null,
      "token_tukang": "eXdDlWuml1I:APA91bFmkGfc920KtVEW3aTQFmeVz1uoeuk845b_GJHnQrKsVRt_c_YjmXnpEVrWEJYRUqb4cTzPOMN54fnU5XAfWcTJ-VXkcgCK4MjuJ5F_xB_8vCmABNDmaaUr3iSwA3CW-JOwQZkWZUeFh0KMpAXV-oJvlVZl8g",
      "image_order": "test",
      "title_order": "test",
      "alamat_detail_order": "test",
      "altitude_alamat": "89",
      "latitude_alamat": "89",
      "telp_alternatif": "test",
      "detail_deskripsi_order": "test",
      "catatan_tambahan": "test",
      "tgl_pengerjaan": null,
      "tgl_selesai": null,
      "tgl_selesai_close": null,
      "tgl_order_dibuat": null,
      "status": "waiting",
      "harga_total": null,
      "harga_transfer": "5000",
      "telp_tukang": "+6281235133535",
      "urutan_harga": "1",
      "saran_pesan": null,
      "is_taken": "N",
      "is_deal": "",
      "foto_pembayaran": null,
      "rating": "5",
      "biaya_fixed": null,
      "kategori": "Pompa Air",
      "waktu_selesai_garansi": null,
      "batas_waktu_pembayaran": null,
      "sudah_bayar": null,
      "sudah_upload": "0",
      "tgl_bayar": null,
      "expiry": "NO",
      "nama_customer": "yekti",
      "alamat_customer": null,
      "email": "yektiasmoro@stiki.ac.id",
      "tgl_daftar": "2018-07-18 19:57:34",
      "id_customer": null,
      "tgl_lahir": null,
      "foto_customer": null,
      "point": null,
      "nama_tukang": "Test2",
      "alamat_tukang": "test",
      "foto_ktp": "",
      "no_ktp": "",
      "foto_tukang": "",
      "jumlah_Pengerjaan": "6",
      "jumlah_nilai": "30"
    }
    ?>